### ISSUE TITLE
Deepslate Salt Ore makes no sound

### ISSUE THREAD

**Issue by 062regrahc** [DarkBumus/SaltyMod-Expanded#2]
self-explanatory. Deepslate Salt Ore does not make any sound while being mined or when broken.

**Comment by Roadhog360** [comment]
This will be fixed from Et Futurum's end in 2.6.0, since [0ef63b6](https://github.com/Roadhog360/Et-Futurum-Requiem/commit/0ef63b653368982f1a74aa979921f969d4899314).
